import { Injectable, signal } from '@angular/core';
import { environment } from '../environments/environment';
import type { TtsProvider } from '../models/voice.model';

/**
 * Speech OUTPUT. Wraps the Web Speech Synthesis API (V1 default) and can
 * alternatively play audio generated by the backend's OpenAI TTS endpoint.
 * Deliberately not hard-coded to one provider (see EdithSettings.ttsProvider)
 * so the app can switch strategies without touching call sites.
 *
 * Audio plays through the standard HTMLAudio/SpeechSynthesis output path,
 * which is what lets iOS route sound to a connected Bluetooth
 * headset/glasses -- this app never talks to Bluetooth directly.
 */
@Injectable({ providedIn: 'root' })
export class AudioService {
  readonly speaking = signal(false);
  readonly ttsSupported = signal(this.detectSpeechSynthesis());
  readonly voices = signal<SpeechSynthesisVoice[]>([]);

  private currentAudioEl: HTMLAudioElement | null = null;

  constructor() {
    if (this.ttsSupported()) {
      const loadVoices = () => this.voices.set(speechSynthesis.getVoices());
      loadVoices();
      // Safari loads voices asynchronously
      speechSynthesis.onvoiceschanged = loadVoices;
    }
  }

  private detectSpeechSynthesis(): boolean {
    return typeof window !== 'undefined' && 'speechSynthesis' in window;
  }

  /**
   * Speaks `text` aloud using the selected provider. Resolves once playback
   * finishes (or immediately on failure, after surfacing the error).
   */
  async speak(
    text: string,
    opts: { provider: TtsProvider; voiceURI?: string | null; rate?: number } = { provider: 'browser' },
  ): Promise<void> {
    this.stop();
    if (!text.trim()) return;

    if (opts.provider === 'openai') {
      return this.speakViaOpenAI(text);
    }
    return this.speakViaBrowser(text, opts.voiceURI ?? null, opts.rate ?? 1);
  }

  private speakViaBrowser(text: string, voiceURI: string | null, rate: number): Promise<void> {
    if (!this.ttsSupported()) {
      return Promise.reject(new Error('Speech synthesis is not supported in this browser.'));
    }
    return new Promise((resolve, reject) => {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = rate;
      const voice = voiceURI ? this.voices().find((v) => v.voiceURI === voiceURI) : undefined;
      if (voice) utterance.voice = voice;

      utterance.onstart = () => this.speaking.set(true);
      utterance.onend = () => {
        this.speaking.set(false);
        resolve();
      };
      utterance.onerror = (e) => {
        this.speaking.set(false);
        // "interrupted"/"canceled" happen on intentional stop() calls - not real errors
        if (e.error === 'interrupted' || e.error === 'canceled') resolve();
        else reject(new Error(`Speech playback failed: ${e.error}`));
      };

      speechSynthesis.speak(utterance);
    });
  }

  private async speakViaOpenAI(text: string): Promise<void> {
    const response = await fetch(`${environment.apiBaseUrl}/tts`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text }),
    });
    if (!response.ok) {
      throw new Error(`Server speech synthesis failed (${response.status})`);
    }
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const audio = new Audio(url);
    this.currentAudioEl = audio;

    return new Promise((resolve, reject) => {
      audio.onplay = () => this.speaking.set(true);
      audio.onended = () => {
        this.speaking.set(false);
        URL.revokeObjectURL(url);
        resolve();
      };
      audio.onerror = () => {
        this.speaking.set(false);
        URL.revokeObjectURL(url);
        reject(new Error('Audio playback failed'));
      };
      audio.play().catch(reject);
    });
  }

  /** Stops any in-progress speech immediately (used by the Stop button). */
  stop(): void {
    if (this.ttsSupported() && speechSynthesis.speaking) {
      speechSynthesis.cancel();
    }
    if (this.currentAudioEl) {
      this.currentAudioEl.pause();
      this.currentAudioEl = null;
    }
    this.speaking.set(false);
  }
}
